### PR TITLE
Support for being a group only provider

### PR DESCRIPTION
**Pull request by keul**
Apart various minimal fixes, this PR fix a limitation of the current implementation: it's not possibible to use this PAS plugin as a group only provider: until now users must be managed by the databases itself.

### CODE REVIEW

**Comment by keul** [comment]
Sorry @jensens, are you the one to ping for this add-on? I've this PR stale here for ages and I need this again for a customer.

**Comment by jensens** [comment]
In fact I was in the same situation and just headed forward by doing the necessary changes. I propose you do the same. I can do a quick review if you want...

**Comment by keul** [comment]
@jensens sorry I didn't get it. You mean that master is already supporting group-only mode?

**Comment by jensens** [comment]
Sorry, no, what I really want to say is that you should just go on.

**Pull request merged**
